consegna5COMMENTATA: consegna5COMMENTATA.o
	gcc -o prova consegna5COMMENTATA.o

consegna5COMMENTATA.o: consegna5COMMENTATA.c consegna5COMMENTATA.h
	gcc -c consegna5COMMENTATA.c

clean:
	rm *.o consegna5COMMENTATA